// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web; // Use web config for Windows desktop
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_0wqugIwqcHbiYbf_X05E6ubJ2iNrW84',
    appId: '1:724307882773:web:b0bac5102e068e5b966f1c',
    messagingSenderId: '724307882773',
    projectId: 'harara-253af',
    authDomain: 'harara-253af.firebaseapp.com',
    storageBucket: 'harara-253af.firebasestorage.app',
    measurementId: 'G-8PPV47MED1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBms_ZIUamwgJMHczaJlJeckCEuzAPejqw',
    appId: '1:724307882773:android:7d2771b2fe3fcec7966f1c',
    messagingSenderId: '724307882773',
    projectId: 'harara-253af',
    storageBucket: 'harara-253af.firebasestorage.app',
  );
}
